"""Compare one mod's prototypes across two --dump-data runs.

The data stage silently ignores properties it doesn't recognise, so a 2.1-only
property in a 2.0 build loads clean and does nothing. That gap is invisible in
the log and shows up only by diffing what each game version actually built.

    python compare-dumps.py dump-2.0.json dump-2.1.json --prefix pure-

Prints, per prototype, every leaf property whose value differs or is missing on
one side. Differences inside prototypes the mod did not author (recycling
recipes generated by the quality mod, for instance) are engine drift, not port
work - read the names before acting.
"""

import argparse
import json


def load(path, prefix):
    """Flatten a data-raw dump to {(prototype_type, name): prototype}."""
    raw = json.load(open(path, encoding="utf-8"))
    out = {}
    for ptype, entries in raw.items():
        if not isinstance(entries, dict):
            continue
        for name, proto in entries.items():
            if prefix in name:
                out[(ptype, name)] = proto
    return out


def leaves(node, path=""):
    """Every scalar in a nested structure, keyed by its json-pointer-ish path."""
    if isinstance(node, dict):
        out = {}
        for key, value in node.items():
            out.update(leaves(value, path + "/" + str(key)))
        return out
    if isinstance(node, list):
        out = {}
        for index, value in enumerate(node):
            out.update(leaves(value, path + "/" + str(index)))
        return out
    return {path: node}


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("old", help="dump from the older game version")
    ap.add_argument("new", help="dump from the newer game version")
    ap.add_argument("--prefix", required=True,
                    help="substring identifying the mod's prototypes, e.g. 'pure-'")
    ap.add_argument("--skip", nargs="*", default=["/filename", "/icon", "/graph"],
                    help="path fragments to ignore (sprite paths differ harmlessly)")
    ap.add_argument("--max", type=int, default=40, help="differences printed per prototype")
    args = ap.parse_args()

    old, new = load(args.old, args.prefix), load(args.new, args.prefix)
    print("%s: %d prototypes    %s: %d prototypes" % (args.old, len(old), args.new, len(new)))

    for label, missing in (("only in " + args.new, set(new) - set(old)),
                           ("only in " + args.old, set(old) - set(new))):
        if missing:
            print("\n!! %s: %s" % (label, ", ".join("%s %s" % k for k in sorted(missing))))

    total = 0
    for key in sorted(set(old) & set(new)):
        a, b = leaves(old[key]), leaves(new[key])
        diffs = []
        for leaf in sorted(set(a) | set(b)):
            if any(s in leaf for s in args.skip):
                continue
            va, vb = a.get(leaf, "<absent>"), b.get(leaf, "<absent>")
            if va != vb:
                diffs.append("    %s : old=%r  new=%r" % (leaf, va, vb))
        if diffs:
            total += len(diffs)
            print("\n## %s %s" % key)
            print("\n".join(diffs[:args.max]))
            if len(diffs) > args.max:
                print("    ... %d more" % (len(diffs) - args.max))

    if not total:
        print("\nNo property differences. Engine *behaviour* differences are still possible - "
              "see references/2.1-breaking-changes.md.")


if __name__ == "__main__":
    main()
